const CategoryData = [
    {
        id:1,
        name:'Island',
        icon:'https://img.icons8.com/ios-filled/50/island-on-water.png'
    },
    {
        id:2,
        name:'Desert',
        icon:'https://img.icons8.com/external-basicons-line-edtgraphics/50/external-cactus-outdoors-basicons-line-edtgraphics.png'
    },
    {
        id:3,
        name:'Beach',
        icon:'https://img.icons8.com/dotty/50/beach.png'
    },
    {
        id:4,
        name:'Mountain',
        icon:'https://img.icons8.com/ios-filled/50/mountain.png'
    },
    {
        id:5,
        name:'City',
        icon:'https://img.icons8.com/ios-glyphs/60/city-buildings.png'
    },
    {
        id:6,
        name:"Pray",
        icon:"https://img.icons8.com/ios-filled/50/prayer.png"
    },
    {
        id:7,
        name:"Tratment",
        icon:"https://img.icons8.com/ios-filled/50/hospital.png"
    },
    {
        id:8,
        name:"Visa",
        icon:"https://img.icons8.com/ios-filled/50/passport.png"
    }
]

export default CategoryData